### ISSUE TITLE
No connection to unifi possible

### ISSUE THREAD

**Issue by Friedi1970** [steffjenl/com.ubnt.unifi#11]
I think this is since the “new” login of Unifi OS.
Anyway, it is impossible for me to log the app in. Always connect and disconect. 

Maybe it is just a setting issue but I really found no solution at all.

**Comment by thorleifjaocbsen** [comment]
I have a issue where the app shows a Pause icon, and i have to restart it multiple times a day for it to work only a small amount of time. @steffjenl  any idea ? Do you see this problem yourself?

**Comment by ronwell74** [comment]
I have the same issue of not being able to login and get the app to connect

**Comment by Friedi1970** [comment]
You wrote on every rating of your app at the homey store “We don't support UDM 1.9.x please contact Ubiquiti to make there API public!”.
To be honest I don’t know what you are talking about, as I never had a UDM.

So, please tell me what exactly is the problem. I can’t reach out at Ubiquity without further information.
